### ISSUE TITLE
IIIF Collection Server - Open sourcing

### ISSUE THREAD

**Issue by 4d4mm** [digirati-co-uk/iiif-collection-server#1]
## About this project

IIIF Collection Server

[https://github.com/digirati-co-uk/iiif-collection-server](https://github.com/digirati-co-uk/iiif-collection-server)

Technical Lead: Tom Crane
Project manager: Ian Farquhar

## Checklist from [rfc-2](https://github.com/digirati-co-uk/rfc/tree/master/rfc/rfc2---open-source-standards)
- [x] Code quality - minimum standard of formatting and style for language(s)
- [x] Code quality - minimum test coverage and other applicable metrics
- [x] Readme - inclusion of `README.md`
- [x] Readme - project purpose and description
- [x] Readme - minimum requirements and dependencies
- [x] Readme - links / references to significant dependencies 
- [x] Readme - build and deployment instructions
- [x] Readme - configuration and / or initial set up steps
- [x] Readme - inclusion of versioning system 
- [x] License - inclusion of previously or newly approved `LICENSE.md`
- [x] License - updated with correct copyright, year and contact information
- [x] Contributing - inclusion of `CONTRIBUTING.md` 
- [x] Listed in Confluence

**Comment by 4d4mm** [comment]
@tomcrane as I mentioned before, I've finished with the preparations for open sourcing, please have a look and let me know if you need anything else before I make the repository public.

Latest build:
https://travis-ci.com/digirati-co-uk/iiif-collection-server/jobs/182850032

Public deployment:
https://iiif-collection.ch.digtest.co.uk/p3/

Coverage:
```
----------- coverage: platform linux, python 3.6.3-final-0 -----------
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
iiif_collection_server/__init__.py                 0      0   100%
iiif_collection_server/constants.py                2      0   100%
iiif_collection_server/iiif_serializer.py         34      1    97%
iiif_collection_server/manifest_processor.py      29      1    97%
iiif_collection_server/s3.py                      32      1    97%
iiif_collection_server/settings.py                 6      0   100%
------------------------------------------------------------------
TOTAL                                            103      3    97%
```

**Comment by tomcrane** [comment]
LGTM, run locally

btw the readme mentions an `app` dir but there isn't one. Minor detail.

Open source good to go.

**Comment by 4d4mm** [comment]
Oh yeah I update the folder name. If you check the git history, renamed it form the generic `app` in the last few commits...
